#!/bin/bash
# clang -O0 -emit-llvm -c strength.c 
# llvm-dis strength.bc
# opt -load ./LocalOpts.so -local-opts strength.bc -o strength-opt.ll -S

clang -Xclang -disable-O0-optnone -O0 -emit-llvm -c strength.c -o strength.bc 
llvm-dis strength.bc
opt -mem2reg strength.bc -o strength-m2r.bc
llvm-dis strength-m2r.bc
opt -load ./LocalOpts.so -local-opts strength-m2r.bc -o strength-m2r-opt.ll -S 
